
export const ADD_CITIES_CLOCK = 'ADD_CITIES_CLOCK'
export const LOADING = 'LOADING'

export const LOAD_CITIES = 'LOAD_CITIES'
export const ADD_CITIES = 'ADD_CITIES'
export const REMOVE_CITIES = 'DELETE_CITIES'

export const LOAD_SELECTED_CITIES = 'LOAD_SELECTED_CITIES'
export const ADD_SELECTED_CITIES = 'ADD_SELECTED_CITIES'
export const REMOVE_SELECTED_CITIES = 'REMOVE_SELECTED_CITIES'

export const LOAD_CURRENT_UTC_DATETIME = 'LOAD_CURRENT_UTC_DATETIME'

export const LOAD_LANGUAGE = 'LOAD_LANGUAGE'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
